apiVersion: v1
kind: Service
metadata:
  name: crud-api-service
  labels:
    app: crud-api
spec:
  type: NodePort  # 외부 접근을 위한 NodePort
  selector:
    app: crud-api
  ports:
  - protocol: TCP
    port: 80          # 서비스 포트
    targetPort: 8080  # 컨테이너 포트
    nodePort: 30080   # 외부 접근 포트 (192.168.1.55:30080)
    name: http
